name: hydrabot-pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint Check
      run: |
        isort src/. -c
        black src/ --check

    - name: Mypy Check
      run: |
        mypy src/. --config-file=mypy.ini

    - name: Build docs
      run: |
        cd docs
        make html
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Test
      env:
        DATABASE_URI: postgresql://hydrabot:test@localhost/hydrabot-test
        WALLET_PRIVATE_KEY: 9ab9241d2c321ab7f3235804888831f23f63145d738643397b7c8eed48d1f3a7
        WEB3_PROVIDER_URL: http://localhost
        LISTEN_CHANNEL_ID: 11111
        BASESCAN_API_KEY: API_KEY
        USER_IDS: 1337
      run: |
        pytest src/.

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: hydrabot
          POSTGRES_PASSWORD: test
          POSTGRES_DB: hydrabot-test
        ports:
          - 5432:5432
